svg_tags = [
    "a",
    "animate",
    "animateMotion",
    "animateTransform",
    "audio",
    "canvas",
    "circle",
    "clipPath",
    "defs",
    "desc",
    "discard",
    "ellipse",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feDistantLight",
    "feDropShadow",
    "feFlood",
    "feFuncA",
    "feFuncB",
    "feFuncG",
    "feFuncR",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMergeNode",
    "feMorphology",
    "feOffset",
    "fePointLight",
    "feSpecularLighting",
    "feSpotLight",
    "feTile",
    "feTurbulence",
    "filter",
    "foreignObject",
    "g",
    "iframe",
    "image",
    "line",
    "linearGradient",
    "marker",
    "mask",
    "metadata",
    "mpath",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "radialGradient",
    "rect",
    "script",
    "set",
    "stop",
    "style",
    "svg",
    "switch",
    "symbol",
    "text",
    "textPath",
    "title",
    "tspan",
    "unknown",
    "use",
    "video",
    "view",
]

svg_tags_use = [
    "animate",
    "animateMotion",
    "animateTransform",
    "circle",
    "clipPath",
    "defs",
    "desc",
    "discard",
    "ellipse",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feDistantLight",
    "feDropShadow",
    "feFlood",
    "feFuncA",
    "feFuncB",
    "feFuncG",
    "feFuncR",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMergeNode",
    "feMorphology",
    "feOffset",
    "fePointLight",
    "feSpecularLighting",
    "feSpotLight",
    "feTile",
    "feTurbulence",
    "filter",
    "foreignObject",
    "g",
    "image",
    "line",
    "linearGradient",
    "marker",
    "mask",
    "metadata",
    "mpath",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "radialGradient",
    "rect",
    "set",
    "stop",
    "svg",
    "switch",
    "symbol",
    "text",
    "textPath",
    "tspan",
    "use",
    "view",
]

svg_presentation_attributes = [
    "alignment-baseline",
    "baseline-shift",
    "clip",
    "clip-path",
    "clip-rule",
    "color",
    "color-interpolation",
    "color-interpolation-filters",
    "color-profile",
    "color-rendering",
    "cursor",
    "direction",
    "display",
    "dominant-baseline",
    "enable-background",
    "fill",
    "fill-opacity",
    "fill-rule",
    "filter",
    "flood-color",
    "flood-opacity",
    "font-family",
    "font-size",
    "font-size-adjust",
    "font-stretch",
    "font-style",
    "font-variant",
    "font-weight",
    "glyph-orientation-horizontal",
    "glyph-orientation-vertical",
    "image-rendering",
    "kerning",
    "letter-spacing",
    "lighting-color",
    "marker-end",
    "marker-mid",
    "marker-start",
    "mask",
    "opacity",
    "overflow",
    "pointer-events",
    "shape-rendering",
    "stop-color",
    "stop-opacity",
    "stroke",
    "stroke-dasharray",
    "stroke-dashoffset",
    "stroke-linecap",
    "stroke-linejoin",
    "stroke-miterlimit",
    "stroke-opacity",
    "stroke-width",
    "text-anchor",
    "transform",
    "text-decoration",
    "text-rendering",
    "unicode-bidi",
    "vector-effect",
    "visibility",
    "word-spacing",
    "writing-mode",
    "cx",
    "cy",
    "r",
    "rx",
    "ry",
    "d",
    "fill",
    "transform",
]

svg_filter_attributes = [
    "height",
    "result",
    "width",
    "x",
    "y",
    "type",
    "tableValues",
    "slope",
    "intercept",
    "amplitude",
    "exponent",
    "offset",
    "xlink:href",
]

svg_animation_attributes = [
    "attributeType",
    "attributeName",
    "begin",
    "dur",
    "end",
    "min",
    "max",
    "restart",
    "repeatCount",
    "repeatDur",
    "fill",
    "calcMode",
    "values",
    "keyTimes",
    "keySplines",
    "from",
    "to",
    "by",
    "additive",
    "accumulate",
]

svg_attr_dict = {
    "a": ["download", "requiredExtensions", "role", "systemLanguage"],
    "animate": [
        "accumulate",
        "additive",
        "attributeName",
        "begin",
        "by",
        "calcMode",
        "dur",
        "end",
        "fill",
        "from",
        "href",
        "keySplines",
        "keyTimes",
        "max",
        "min",
        "repeatCount",
        "repeatDur",
        "requiredExtensions",
        "restart",
        "systemLanguage",
        "to",
        "values",
    ],
    "animateMotion": [
        "accumulate",
        "additive",
        "begin",
        "by",
        "calcMode",
        "dur",
        "end",
        "fill",
        "from",
        "href",
        "keyPoints",
        "keySplines",
        "keyTimes",
        "max",
        "min",
        "origin",
        "path",
        "repeatCount",
        "repeatDur",
        "requiredExtensions",
        "restart",
        "rotate",
        "systemLanguage",
        "to",
        "values",
    ],
    "animateTransform": [
        "accumulate",
        "additive",
        "attributeName",
        "begin",
        "by",
        "calcMode",
        "dur",
        "end",
        "fill",
        "from",
        "href",
        "keySplines",
        "keyTimes",
        "max",
        "min",
        "repeatCount",
        "repeatDur",
        "requiredExtensions",
        "restart",
        "systemLanguage",
        "to",
        "type",
        "values",
    ],
    "audio": ["requiredExtensions", "role", "systemLanguage"],
    "canvas": ["preserveAspectRatio", "requiredExtensions", "role", "systemLanguage"],
    "circle": ["pathLength", "requiredExtensions", "role", "systemLanguage"],
    "clipPath": ["clipPathUnits", "requiredExtensions", "systemLanguage"],
    "discard": ["begin", "href", "requiredExtensions", "role", "systemLanguage"],
    "ellipse": ["pathLength", "requiredExtensions", "role", "systemLanguage"],
    "feBlend": ["height", "in", "in2", "mode", "result", "width", "x", "y"],
    "feColorMatrix": ["height", "in", "result", "type", "values", "width", "x", "y"],
    "feComponentTransfer": ["height", "in", "result", "width", "x", "y"],
    "feComposite": [
        "height",
        "in",
        "in2",
        "k1",
        "k2",
        "k3",
        "k4",
        "operator",
        "result",
        "width",
        "x",
        "y",
    ],
    "feConvolveMatrix": [
        "bias",
        "divisor",
        "edgeMode",
        "height",
        "in",
        "kernelMatrix",
        "kernelUnitLength",
        "order",
        "preserveAlpha",
        "result",
        "targetX",
        "targetY",
        "width",
        "x",
        "y",
    ],
    "feDiffuseLighting": [
        "diffuseConstant",
        "height",
        "in",
        "kernelUnitLength",
        "result",
        "surfaceScale",
        "width",
        "x",
        "y",
    ],
    "feDisplacementMap": [
        "height",
        "in",
        "in2",
        "result",
        "scale",
        "width",
        "x",
        "xChannelSelector",
        "y",
        "yChannelSelector",
    ],
    "feDistantLight": ["azimuth", "elevation"],
    "feDropShadow": [
        "dx",
        "dy",
        "height",
        "in",
        "result",
        "stdDeviation",
        "width",
        "x",
        "y",
    ],
    "feFlood": ["height", "result", "width", "x", "y"],
    "feFuncA": [
        "amplitude",
        "exponent",
        "intercept",
        "offset",
        "slope",
        "tableValues",
        "type",
    ],
    "feFuncB": [
        "amplitude",
        "exponent",
        "intercept",
        "offset",
        "slope",
        "tableValues",
        "type",
    ],
    "feFuncG": [
        "amplitude",
        "exponent",
        "intercept",
        "offset",
        "slope",
        "tableValues",
        "type",
    ],
    "feFuncR": [
        "amplitude",
        "exponent",
        "intercept",
        "offset",
        "slope",
        "tableValues",
        "type",
    ],
    "feGaussianBlur": [
        "edgeMode",
        "height",
        "in",
        "result",
        "stdDeviation",
        "width",
        "x",
        "y",
    ],
    "feImage": [
        "crossorigin",
        "height",
        "href",
        "preserveAspectRatio",
        "result",
        "width",
        "x",
        "y",
    ],
    "feMerge": ["height", "result", "width", "x", "y"],
    "feMergeNode": ["in"],
    "feMorphology": ["height", "in", "operator", "radius", "result", "width", "x", "y"],
    "feOffset": ["dx", "dy", "height", "in", "result", "width", "x", "y"],
    "fePointLight": ["x", "y", "z"],
    "feSpecularLighting": [
        "height",
        "in",
        "kernelUnitLength",
        "result",
        "specularConstant",
        "specularExponent",
        "surfaceScale",
        "width",
        "x",
        "y",
    ],
    "feSpotLight": [
        "limitingConeAngle",
        "pointsAtX",
        "pointsAtY",
        "pointsAtZ",
        "specularExponent",
        "x",
        "y",
        "z",
    ],
    "feTile": ["height", "in", "result", "width", "x", "y"],
    "feTurbulence": [
        "baseFrequency",
        "height",
        "numOctaves",
        "result",
        "seed",
        "stitchTiles",
        "type",
        "width",
        "x",
        "y",
    ],
    "filter": ["filterUnits", "height", "primitiveUnits", "width", "x", "y"],
    "foreignObject": ["requiredExtensions", "role", "systemLanguage"],
    "g": ["requiredExtensions", "role", "systemLanguage"],
    "iframe": ["requiredExtensions", "role", "systemLanguage"],
    "image": [
        "crossorigin",
        "href",
        "preserveAspectRatio",
        "requiredExtensions",
        "role",
        "systemLanguage",
    ],
    "line": [
        "pathLength",
        "requiredExtensions",
        "role",
        "systemLanguage",
        "x1",
        "x2",
        "y1",
        "y2",
    ],
    "linearGradient": [
        "gradientTransform",
        "gradientUnits",
        "href",
        "spreadMethod",
        "x1",
        "x2",
        "y1",
        "y2",
    ],
    "marker": [
        "markerHeight",
        "markerUnits",
        "markerWidth",
        "orient",
        "preserveAspectRatio",
        "refX",
        "refY",
        "viewBox",
    ],
    "mask": [
        "height",
        "maskContentUnits",
        "maskUnits",
        "requiredExtensions",
        "systemLanguage",
        "width",
        "x",
        "y",
    ],
    "mpath": ["href"],
    "path": ["pathLength", "requiredExtensions", "role", "systemLanguage"],
    "pattern": [
        "height",
        "href",
        "patternContentUnits",
        "patternTransform",
        "patternUnits",
        "preserveAspectRatio",
        "viewBox",
        "width",
        "x",
        "y",
    ],
    "polygon": ["pathLength", "points", "requiredExtensions", "role", "systemLanguage"],
    "polyline": [
        "pathLength",
        "points",
        "requiredExtensions",
        "role",
        "systemLanguage",
    ],
    "radialGradient": [
        "cx",
        "cy",
        "fr",
        "fx",
        "fy",
        "gradientTransform",
        "gradientUnits",
        "href",
        "r",
        "spreadMethod",
    ],
    "rect": ["pathLength", "requiredExtensions", "role", "systemLanguage"],
    "script": ["href"],
    "set": [
        "attributeName",
        "begin",
        "dur",
        "end",
        "fill",
        "href",
        "max",
        "min",
        "repeatCount",
        "repeatDur",
        "requiredExtensions",
        "restart",
        "systemLanguage",
        "to",
    ],
    "stop": ["offset"],
    "style": ["media"],
    "svg": [
        "playbackorder",
        "preserveAspectRatio",
        "requiredExtensions",
        "role",
        "systemLanguage",
        "timelinebegin",
        "transform",
        "viewBox",
        "zoomAndPan",
        "xmlns",
        "version",
    ],
    "switch": ["requiredExtensions", "role", "systemLanguage"],
    "symbol": ["preserveAspectRatio", "refX", "refY", "role", "viewBox"],
    "text": [
        "dx",
        "dy",
        "lengthAdjust",
        "requiredExtensions",
        "role",
        "rotate",
        "systemLanguage",
        "textLength",
        "x",
        "y",
    ],
    "textPath": [
        "href",
        "lengthAdjust",
        "method",
        "path",
        "requiredExtensions",
        "role",
        "side",
        "spacing",
        "startOffset",
        "systemLanguage",
        "textLength",
    ],
    "tspan": [
        "dx",
        "dy",
        "lengthAdjust",
        "requiredExtensions",
        "role",
        "rotate",
        "systemLanguage",
        "textLength",
        "x",
        "y",
    ],
    "unknown": ["requiredExtensions", "role", "systemLanguage"],
    "use": ["href", "requiredExtensions", "role", "systemLanguage"],
    "video": ["requiredExtensions", "role", "systemLanguage"],
    "view": ["preserveAspectRatio", "role", "viewBox", "zoomAndPan"],
}
